.global vectortable
.balign 0x800
vectortable:
.balign 0x80
  b hang
.balign 0x80
  b hang
.balign 0x80
  b hang
.balign 0x80
  b hang

.balign 0x80
  b hang
.balign 0x80
  b hang
.balign 0x80
  b hang
.balign 0x80
  b hang

.balign 0x80
  b hang
.balign 0x80
  b hang
.balign 0x80
  b hang
.balign 0x80
  b hang

.balign 0x80
  b hang
.balign 0x80
  b hang
.balign 0x80
  b hang
.balign 0x80
  b hang
