name: aarch64-os CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install gcc-aarch64-linux-gnu
    - name: make
      run: make kernel8.elf
